### ISSUE TITLE
http://deeplearnphysics.org does not display properly

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/DeepLearnPhysics.github.io#3]
This is a follow up of merging the pull request https://github.com/DeepLearnPhysics/DeepLearnPhysics.github.io/pull/2

**Comment by drinkingkazu** [comment]
Reported by @coreyjadams there:

Forgive my complete ignorance of https etc.  But when I access deeplearnphysics.org, I see the site like this:

![image](https://user-images.githubusercontent.com/6619961/33950223-8242c3ee-dff1-11e7-93e4-ee784531e48c.png)

Further, the links are broken because the redirect to the https domain name.  Am I doing something wrong?

**Comment by drinkingkazu** [comment]
@coreyjadams this is likely my lack of knowledge so bare with me please! Do you see a difference when you access https://deeplearnphysics.org vs. www.deeplearnphysics.org vs. http://deeplearnphysics.org ?

**Comment by Temigo** [comment]
@drinkingkazu  This is what I experienced before the pull request #2 . I didn't propagate the changes to the master branch, that might be why the issue is still online...

**Comment by drinkingkazu** [comment]
@Temigo is right. Basically she made a change, Kazu merged pull request and forgot to regenerate static sites... just done now and it works for me on chrome! @coreyjadams can you check? it's only main site. I'll go change the DataChallenge site

**Comment by drinkingkazu** [comment]
I fixed it https://github.com/DeepLearnPhysics/DeepLearnPhysics.github.io/commit/2635b60d383c1ab637e6d3327676ebab63cb3ec1 and @Temigo simultaneously fixed https://github.com/DeepLearnPhysics/DeepLearnPhysics.github.io/commit/827b8f09af67d30c0df73288c8dd1d7ae3d30144 and request #4 merged so it's double-fixed lol I'll close this now.
